import type { TravelConfig, GenerationResults } from '../types';
import { formatDateAU, addDaysISO } from './dateUtils';

export function generateEmailBody(config: TravelConfig, results: GenerationResults): string {
  const lines: string[] = [];
  const country = config.country?.name || 'Adventure';

  lines.push(`My ${country} Trip Plan`);
  lines.push('='.repeat(30));
  lines.push('');
  lines.push(`Travellers: ${config.travellers}`);
  lines.push(`Dates: ${formatDateAU(config.departureDate)} to ${formatDateAU(config.returnDate)}`);
  lines.push(`Destinations: ${config.destinations.map(d => d.name).join(', ')}`);
  lines.push('');

  // Itinerary
  if (results.itinerary.length > 0) {
    lines.push('ITINERARY');
    lines.push('-'.repeat(20));
    for (const day of results.itinerary) {
      const date = formatDateAU(addDaysISO(config.departureDate, day.day - 1));
      lines.push(`Day ${day.day} (${date}): ${day.title} - ${day.location}`);
      for (const a of day.activities) {
        lines.push(`  - ${a}`);
      }
    }
    lines.push('');
  }

  // Flights
  if (results.flights.length > 0) {
    lines.push('FLIGHTS TO BOOK');
    lines.push('-'.repeat(20));
    for (const f of results.flights) {
      lines.push(`${f.leg} | ${formatDateAU(f.date)} | ${f.from_code} to ${f.to_code} | ${f.duration} | ${f.price_estimate_aud}/person`);
    }
    lines.push('');
  }

  // Hotels
  if (results.hotels.length > 0) {
    lines.push('HOTELS TO BOOK');
    lines.push('-'.repeat(20));
    for (const dest of results.hotels) {
      lines.push(`${dest.destination}: ${formatDateAU(dest.check_in)} to ${formatDateAU(dest.check_out)} (${dest.nights} nights)`);
      const topPick = dest.hotels.find(h => h.recommended) || dest.hotels[0];
      if (topPick) {
        lines.push(`  Recommended: ${topPick.name} (${topPick.price_per_night_aud}/night)`);
      }
    }
    lines.push('');
  }

  // Budget
  if (results.budget.length > 0) {
    lines.push('BUDGET (per person)');
    lines.push('-'.repeat(20));
    for (const b of results.budget) {
      lines.push(`${b.category}: ${b.cost}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('Generated by Adventure Planner');

  return lines.join('\n');
}

export function openEmailWithTrip(config: TravelConfig, results: GenerationResults) {
  const country = config.country?.name || 'Adventure';
  const subject = encodeURIComponent(`My ${country} Trip Plan - ${formatDateAU(config.departureDate)} to ${formatDateAU(config.returnDate)}`);
  const body = encodeURIComponent(generateEmailBody(config, results));
  window.open(`mailto:?subject=${subject}&body=${body}`, '_self');
}
